package com.netonstream.privchat.sdk.dto

/** Structured LinkMetadata payload. Preview fields are sender-generated; receivers only render them. */
data class LinkMessagePayload(
    val url: String,
    val title: String? = null,
    val description: String? = null,
    val thumbnailFileId: ULong? = null,
)

/**
 * Structured LocationMetadata payload.
 *
 * Phase 2 expands the protocol beyond lat/lng. POI/name/address/thumbnail are generated by
 * the sender-side location provider; receivers must treat absent fields as normal fallback state.
 */
data class LocationMessagePayload(
    val latitude: Double,
    val longitude: Double,
    val coordinateSystem: String? = null,
    val name: String? = null,
    val address: String? = null,
    val poiId: String? = null,
    val poiSource: String? = null,
    val thumbnailFileId: ULong? = null,
)

/** Structured ContactCardMetadata payload. The protocol authority is the user id. */
data class ContactCardMessagePayload(
    val userId: ULong,
)
